# Conectar a MySQL

## Instalación das dependencias

Importante ter instalado con conda: 
* pymysql (para MySQL)
* ipython-sql (para as maxias)
* sqlalchemy (conexión por código)

A contorna de probas neste notebook emprega Python 3.10 (conda create -n bigdata python=3.10. Logo dende conda-forge instalouse: jupyterlab numpy pandas ipykernel ipython beautifulsoup4).

In [1]:
%conda install -y pymysql ipython-sql sqlalchemy

Channels:
 - defaults
Platform: win-64
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done

## Package Plan ##

  environment location: c:\Users\constantin.madalin.i\AppData\Local\miniconda3\envs\programacion

  added / updated specs:
    - ipython-sql
    - pymysql
    - sqlalchemy


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    cryptography-44.0.1        |  py313hbd6ee87_0         1.4 MB
    greenlet-3.1.1             |  py313h5da7b33_0         236 KB
    ipython-sql-0.3.9          |  py313haa95532_0          36 KB
    ipython_genutils-0.2.0     |     pyhd3eb1b0_1          27 KB
    prettytable-3.5.0          |  py313haa95532_0          58 KB
    pymysql-1.0.2              |  py313haa95532_1          96 KB
    sqlalchemy-2.0.37          |  py313h54f65d0_0         6.5 MB
    sqlparse-0.5.2             |  py313haa95532_0         119 KB
    ------------------------------------------------------------
                                           Total:         8.5 MB

The following NEW packages will be INSTALLED:

  cryptography       pkgs/main/win-64::cryptography-44.0.1-py313hbd6ee87_0
  greenlet           pkgs/main/win-64::greenlet-3.1.1-py313h5da7b33_0
  ipython-sql        pkgs/main/win-64::ipython-sql-0.3.9-py313haa95532_0
  ipython_genutils   pkgs/main/noarch::ipython_genutils-0.2.0-pyhd3eb1b0_1
  prettytable        pkgs/main/win-64::prettytable-3.5.0-py313haa95532_0
  pymysql            pkgs/main/win-64::pymysql-1.0.2-py313haa95532_1
  sqlalchemy         pkgs/main/win-64::sqlalchemy-2.0.37-py313h54f65d0_0
  sqlparse           pkgs/main/win-64::sqlparse-0.5.2-py313haa95532_0

The following packages will be UPDATED:

  ca-certificates    conda-forge::ca-certificates-2025.1.3~ --> pkgs/main::ca-certificates-2025.2.25-haa95532_0



Downloading and Extracting Packages: ...working...
sqlalchemy-2.0.37    | 6.5 MB    |            |   0%

cryptography-44.0.1  | 1.4 MB    |            |   0%


greenlet-3.1.1       | 236 KB    |            |   0%



sqlparse-0.5.2       | 119 KB    |            |   0%




pymysql-1.0.2        | 96 KB     |            |   0%





prettytable-3.5.0    | 58 KB     |            |   0%






ipython-sql-0.3.9    | 36 KB     |            |   0%







ipython_genutils-0.2 | 27 KB     |            |   0%
sqlalchemy-2.0.37    | 6.5 MB    |            |   0%



sqlparse-0.5.2       | 119 KB    | #####3     |  54%


greenlet-3.1.1       | 236 KB    | ##7        |  27%




pymysql-1.0.2        | 96 KB     | ########## | 100%




pymysql-1.0.2        | 96 KB     | ########## | 100%



sqlparse-0.5.2       | 119 KB    | ########## | 100%


greenlet-3.1.1       | 236 KB    | ########## | 100%

cryptography-44.0.1  | 1.4 MB    | 1          |   1%







ipython_genutils-0.2 | 27 KB     | #####9     |  60%







ipython_genutils-0.2 | 27 KB     | ########## | 100%
sqlalchemy-2.0.37    | 6.5 MB    | ###2       |  32%

cryptography-44.0.1  | 1.4 MB    | #########7 |  97%

cryptography-44.0.1  | 1.4 MB    | ########## | 100%




pymysql-1.0.2        | 96 KB     | ########## | 100%



sqlparse-0.5.2       | 119 KB    | ########## | 100%
sqlalchemy-2.0.37    | 6.5 MB    | ########## | 100%
sqlalchemy-2.0.37    | 6.5 MB    | ########## | 100%






ipython-sql-0.3.9    | 36 KB     | ####4      |  45%






ipython-sql-0.3.9    | 36 KB     | ########## | 100%







ipython_genutils-0.2 | 27 KB     | ########## | 100%







ipython_genutils-0.2 | 27 KB     | ########## | 100%


greenlet-3.1.1       | 236 KB    | ########## | 100%


greenlet-3.1.1       | 236 KB    | ########## | 100%






ipython-sql-0.3.9    | 36 KB     | ########## | 100%






ipython-sql-0.3.9    | 36 KB     | ########## | 100%





prettytable-3.5.0    | 58 KB     | ##7        |  28%





prettytable-3.5.0    | 58 KB     | ########## | 100%





prettytable-3.5.0    | 58 KB     | ########## | 100%

cryptography-44.0.1  | 1.4 MB    | ########## | 100%
sqlalchemy-2.0.37    | 6.5 MB    | ########## | 100%




































                                                      done
Preparing transaction: done
Verifying transaction: done
Executing transaction: done

Note: you may need to restart the kernel to use updated packages.

==> WARNING: A newer version of conda exists. <==
    current version: 25.1.0
    latest version: 25.1.1

Please update conda by running

    $ conda update -n base -c defaults conda

## Importar librarías e "maxias"

In [27]:
#Librarías para todo o notebook
import pandas as pd
import pymysql
from sqlalchemy import create_engine, text
import requests

#Para as maxias
%load_ext sql

## Creando a cadea de conexión

In [28]:
#Datos de conexión
db_host = "10.133.29.190"
db_port=9906
db_user = "nifi"
db_passwd="nifi.abc123."
db_name="nifi"

#Xerar a cadea de conexión en base aos parámetros anteriores
connectionString=f'mysql+pymysql://{db_user}:{db_passwd}@{db_host}:{db_port}/{db_name}'

## Conectando á BBDD empregando "maxias"

In [20]:
%sql $connectionString

MetaData.__init__() got an unexpected keyword argument 'bind'
Connection info needed in SQLAlchemy format, example:
               postgresql://username:password@hostname/dbname
               or an existing connection: dict_keys([])

### Probando unha consulta

In [21]:
%sql SELECT COUNT(*) FROM trono;

Environment variable $DATABASE_URL not set, and no connect string given.
Connection info needed in SQLAlchemy format, example:
               postgresql://username:password@hostname/dbname
               or an existing connection: dict_keys([])

### Gardando o resultado dunha consulta a unha variable

In [ ]:
dfSQL = %sql SELECT * FROM salaries;
dfSQL.DataFrame().head(5)

<h1>Juegos de tronos<h1>

## Conexión sen maxias

In [94]:
#import sqlalchemy
from sqlalchemy.engine import create_engine

engine = create_engine(connectionString)

cadeaSQL = "SELECT * FROM trono"
#result=engine.execute(cadenaSQL)
dfPanda = pd.read_sql(cadeaSQL, engine)
#dfPanda = pd.read_sql("SELECT * FROM salaries", con=connectionString)
dfPanda.head()

,index,id,firstName,lastName,fullName,title,family,image,imageUrl
0,None,0,Daenerys,None,Daenerys Targaryen,Mother of Dragons,House Targaryen,daenerys.jpg,https://thronesapi.com/assets/images/daenerys.jpg
1,None,1,Samwell,None,Samwell Tarly,Maester,House Tarly,sam.jpg,https://thronesapi.com/assets/images/sam.jpg
2,None,2,Jon,None,Jon Snow,King of the North,House Stark,jon-snow.jpg,https://thronesapi.com/assets/images/jon-snow.jpg
3,None,3,Arya,None,Arya Stark,No One,House Stark,arya-stark.jpg,https://thronesapi.com/assets/images/arya-star...
4,None,4,Sansa,None,Sansa Stark,Lady of Winterfell,House Stark,sansa-stark.jpeg,https://thronesapi.com/assets/images/sansa-sta...

In [85]:
import requests

enderezo = "https://thronesapi.com/api/v2/Characters"
response = requests.get(enderezo)
response.json()

[{'id': 0,
  'firstName': 'Daenerys',
  'lastName': 'Targaryen',
  'fullName': 'Daenerys Targaryen',
  'title': 'Mother of Dragons',
  'family': 'House Targaryen',
  'image': 'daenerys.jpg',
  'imageUrl': 'https://thronesapi.com/assets/images/daenerys.jpg'},
 {'id': 1,
  'firstName': 'Samwell',
  'lastName': 'Tarly',
  'fullName': 'Samwell Tarly',
  'title': 'Maester',
  'family': 'House Tarly',
  'image': 'sam.jpg',
  'imageUrl': 'https://thronesapi.com/assets/images/sam.jpg'},
 {'id': 2,
  'firstName': 'Jon',
  'lastName': 'Snow',
  'fullName': 'Jon Snow',
  'title': 'King of the North',
  'family': 'House Stark',
  'image': 'jon-snow.jpg',
  'imageUrl': 'https://thronesapi.com/assets/images/jon-snow.jpg'},
 {'id': 3,
  'firstName': 'Arya',
  'lastName': 'Stark',
  'fullName': 'Arya Stark',
  'title': 'No One',
  'family': 'House Stark',
  'image': 'arya-stark.jpg',
  'imageUrl': 'https://thronesapi.com/assets/images/arya-stark.jpg'},
 {'id': 4,
  'firstName': 'Sansa',
  'lastName': 'Stark',
  'fullName': 'Sansa Stark',
  'title': 'Lady of Winterfell',
  'family': 'House Stark',
  'image': 'sansa-stark.jpeg',
  'imageUrl': 'https://thronesapi.com/assets/images/sansa-stark.jpeg'},
 {'id': 5,
  'firstName': 'Brandon',
  'lastName': 'Stark',
  'fullName': 'Brandon Stark',
  'title': 'Lord of Winterfell',
  'family': 'House Stark',
  'image': 'bran-stark.jpg',
  'imageUrl': 'https://thronesapi.com/assets/images/bran-stark.jpg'},
 {'id': 6,
  'firstName': 'Ned',
  'lastName': 'Stark',
  'fullName': 'Ned Stark',
  'title': 'Lord of Winterfell',
  'family': 'House Stark',
  'image': 'ned-stark.jpg',
  'imageUrl': 'https://thronesapi.com/assets/images/ned-stark.jpg'},
 {'id': 7,
  'firstName': 'Robert',
  'lastName': 'Baratheon',
  'fullName': 'Robert Baratheon',
  'title': 'Lord of the Seven Kingdoms',
  'family': 'House Baratheon',
  'image': 'robert-baratheon.jpeg',
  'imageUrl': 'https://thronesapi.com/assets/images/robert-baratheon.jpeg'},
 {'id': 8,
  'firstName': 'Jamie',
  'lastName': 'Lannister',
  'fullName': 'Jamie Lannister',
  'title': 'Lord Commander of the Kingsguard',
  'family': 'House Lannister',
  'image': 'jaime-lannister.jpg',
  'imageUrl': 'https://thronesapi.com/assets/images/jaime-lannister.jpg'},
 {'id': 9,
  'firstName': 'Cersei',
  'lastName': 'Lannister',
  'fullName': 'Cersei Lannister',
  'title': 'Lady of Casterly Rock',
  'family': 'House Lannister',
  'image': 'cersei.jpg',
  'imageUrl': 'https://thronesapi.com/assets/images/cersei.jpg'},
 {'id': 10,
  'firstName': 'Cateyln',
  'lastName': 'Stark',
  'fullName': 'Catelyn Stark',
  'title': 'Lady of Winterfell',
  'family': 'House Stark',
  'image': 'catelyn-stark.jpg',
  'imageUrl': 'https://thronesapi.com/assets/images/catelyn-stark.jpg'},
 {'id': 11,
  'firstName': 'Robb',
  'lastName': 'Stark',
  'fullName': 'Rob Stark',
  'title': 'Lord of Winterfell',
  'family': 'House Stark',
  'image': 'robb-stark.jpg',
  'imageUrl': 'https://thronesapi.com/assets/images/robb-stark.jpg'},
 {'id': 12,
  'firstName': 'Theon',
  'lastName': 'Greyjoy',
  'fullName': 'Theon Greyjoy',
  'title': 'Captain of Sea Bitch',
  'family': 'House Greyjoy',
  'image': 'theon.jpg',
  'imageUrl': 'https://thronesapi.com/assets/images/theon.jpg'},
 {'id': 13,
  'firstName': 'Joffrey',
  'lastName': 'Baratheon',
  'fullName': 'Joffrey Baratheon',
  'title': 'Lord of the Seven Kingdoms, Protector of the Realm',
  'family': 'House Lanister',
  'image': 'joffrey.jpg',
  'imageUrl': 'https://thronesapi.com/assets/images/joffrey.jpg'},
 {'id': 14,
  'firstName': 'Tyrion',
  'lastName': 'Lannister',
  'fullName': 'Tyrion Lannister',
  'title': 'Hand of the Queen',
  'family': 'House Lanister',
  'image': 'tyrion-lannister.jpg',
  'imageUrl': 'https://thronesapi.com/assets/images/tyrion-lannister.jpg'},
 {'id': 15,
  'firstName': 'Sandor',
  'lastName': 'Clegane',
  'fullName': 'The Hound',
  'title': 'The Hound',
  'family': 'House Clegane',
  'image': 'the-hound.jpg',
  'imageUrl': 'https://thronesapi.com/assets/images/the-hound.jpg'},
 {'id': 16,
  'firstName': 'Petyr',
  'lastName': 'Baelish',
  'fullName': 'Petyr Baelish',
  'title': 'Littlefinger',
  'family': 'House Baelish',
  'image': 'littlefinger.jpg',
  'imageUrl': 'https://thronesapi.com/assets/images/littlefinger.jpg'},
 {'id': 17,
  'firstName': 'Davos',
  'lastName': 'Seaworth',
  'fullName': 'Davos Seaworth',
  'title': 'Hand of the King',
  'family': 'House Seaworth',
  'image': 'davos-seaworth.png',
  'imageUrl': 'https://thronesapi.com/assets/images/davos-seaworth.png'},
 {'id': 18,
  'firstName': 'Stannis',
  'lastName': 'Baratheon',
  'fullName': 'Stannis Baratheon',
  'title': 'Lord of Dragonstone',
  'family': 'House Baratheon',
  'image': 'stannis.jpg',
  'imageUrl': 'https://thronesapi.com/assets/images/stannis.jpg'},
 {'id': 19,
  'firstName': 'Varys',
  'lastName': 'Unknown',
  'fullName': 'Varys',
  'title': 'Master of Whisperers',
  'family': 'Unknown',
  'image': 'varys.jpg',
  'imageUrl': 'https://thronesapi.com/assets/images/varys.jpg'},
 {'id': 20,
  'firstName': 'Khal',
  'lastName': 'Drogo',
  'fullName': 'Khal Drogo',
  'title': 'Khal',
  'family': 'House Targaryen',
  'image': 'khal-drogo.jpg',
  'imageUrl': 'https://thronesapi.com/assets/images/khal-drogo.jpg'},
 {'id': 21,
  'firstName': 'Margaery',
  'lastName': 'Tyrell',
  'fullName': 'Margaery Tyrell',
  'title': 'Queen of the Seven Kingdoms',
  'family': 'House Tyrell',
  'image': 'margaery-tyrell.jpg',
  'imageUrl': 'https://thronesapi.com/assets/images/margaery-tyrell.jpg'},
 {'id': 22,
  'firstName': 'Ygritte',
  'lastName': 'None',
  'fullName': 'Ygritte',
  'title': 'Spearwife',
  'family': 'Free Folk',
  'image': 'ygritte.jpg',
  'imageUrl': 'https://thronesapi.com/assets/images/ygritte.jpg'},
 {'id': 23,
  'firstName': 'Brienne',
  'lastName': 'Tarth',
  'fullName': 'Brienne of Tarth',
  'title': 'Lady Brienne',
  'family': 'Tarth',
  'image': 'brienne-tarth.jpeg',
  'imageUrl': 'https://thronesapi.com/assets/images/brienne-tarth.jpeg'},
 {'id': 24,
  'firstName': 'Missandei',
  'lastName': 'None',
  'fullName': 'Missandei',
  'title': "Queen's Personal Advisor",
  'family': 'Naathi',
  'image': 'missandei.jpeg',
  'imageUrl': 'https://thronesapi.com/assets/images/missandei.jpeg'},
 {'id': 25,
  'firstName': 'Gilly',
  'lastName': 'None',
  'fullName': 'Gilly',
  'title': 'The Rabbit Keeper',
  'family': 'None',
  'image': 'gilly.jpg',
  'imageUrl': 'https://thronesapi.com/assets/images/gilly.jpg'},
 {'id': 26,
  'firstName': 'Viserys',
  'lastName': 'Targaryan',
  'fullName': 'Viserys Targaryn',
  'title': 'King Viserys III',
  'family': 'Targaryan',
  'image': 'viserys-targaryan.jpg',
  'imageUrl': 'https://thronesapi.com/assets/images/viserys-targaryan.jpg'},
 {'id': 27,
  'firstName': 'Rickon',
  'lastName': 'Stark',
  'fullName': 'Rickon Stark',
  'title': 'Prince',
  'family': 'Stark',
  'image': 'rickon.jpg',
  'imageUrl': 'https://thronesapi.com/assets/images/rickon.jpg'},
 {'id': 28,
  'firstName': 'Roose',
  'lastName': 'Bolton',
  'fullName': 'Roose Bolton',
  'title': 'Lord of Dreadfort',
  'family': 'Bolton',
  'image': 'roose-bolton.jpg',
  'imageUrl': 'https://thronesapi.com/assets/images/roose-bolton.jpg'},
 {'id': 29,
  'firstName': 'Daario',
  'lastName': 'Naharis',
  'fullName': 'Daario',
  'title': 'Commander of the Second Sons',
  'family': 'Naharis',
  'image': 'daario.jpg',
  'imageUrl': 'https://thronesapi.com/assets/images/daario.jpg'},
 {'id': 30,
  'firstName': 'Shae',
  'lastName': '',
  'fullName': 'Shae',
  'title': 'Mistress',
  'family': 'Lorathi',
  'image': 'shae.jpg',
  'imageUrl': 'https://thronesapi.com/assets/images/shae.jpg'},
 {'id': 31,
  'firstName': 'Tommen',
  'lastName': 'Baratheon',
  'fullName': 'Tommen Baratheon',
  'title': 'Prince',
  'family': 'Baratheon',
  'image': 'tommen.jpg',
  'imageUrl': 'https://thronesapi.com/assets/images/tommen.jpg'},
 {'id': 32,
  'firstName': 'Gendry',
  'lastName': 'Baratheon',
  'fullName': 'Gendry Baratheon',
  'title': "Lord of Storm's End",
  'family': 'Baratheon',
  'image': 'gendry.jpg',
  'imageUrl': 'https://thronesapi.com/assets/images/gendry.jpg'},
 {'id': 33,
  'firstName': 'Jorah',
  'lastName': 'Mormont',
  'fullName': 'Jorah Mormont',
  'title': 'Knight',
  'family': 'Mormont',
  'image': 'jorah-mormont.jpg',
  'imageUrl': 'https://thronesapi.com/assets/images/jorah-mormont.jpg'},
 {'id': 34,
  'firstName': 'Robert',
  'lastName': 'Baratheon',
  'fullName': 'Robert Baratheon',
  'title': 'King',
  'family': 'Baratheon',
  'image': 'king-robert.jpg',
  'imageUrl': 'https://thronesapi.com/assets/images/king-robert.jpg'},
 {'id': 35,
  'firstName': 'Ramsey',
  'lastName': 'Bolton',
  'fullName': 'Ramsey Bolton',
  'title': 'The Bastard of Bolton',
  'family': 'Bolton',
  'image': 'ramsey-bolton.jpg',
  'imageUrl': 'https://thronesapi.com/assets/images/ramsey-bolton.jpg'},
 {'id': 36,
  'firstName': 'Talisa',
  'lastName': 'Stark',
  'fullName': 'Talisa Stark',
  'title': 'Queen Consort',
  'family': 'Stark',
  'image': 'talisa-stark.jpg',
  'imageUrl': 'https://thronesapi.com/assets/images/talisa-stark.jpg'},
 {'id': 37,
  'firstName': 'Jeor',
  'lastName': 'Mormont',
  'fullName': 'Jeor Mormont',
  'title': "Lord Commander of the Knight's Watch",
  'family': 'Mormont',
  'image': 'lord-commander-mormont.jpg',
  'imageUrl': 'https://thronesapi.com/assets/images/lord-commander-mormont.jpg'},
 {'id': 38,
  'firstName': 'The High',
  'lastName': 'Sparrow',
  'fullName': 'The High Sparrow',
  'title': 'High Septon',
  'family': 'Sparrow',
  'image': 'the-high-sparrow.jpg',
  'imageUrl': 'https://thronesapi.com/assets/images/the-high-sparrow.jpg'},
 {'id': 39,
  'firstName': 'Oberyn',
  'lastName': 'Martell',
  'fullName': 'Oberyn Martell',
  'title': 'Red Viper of Dorne',
  'family': 'Viper',
  'image': 'red-viper.jpg',
  'imageUrl': 'https://thronesapi.com/assets/images/red-viper.jpg'},
 {'id': 40,
  'firstName': 'Melisandre',
  'lastName': 'The Red Woman',
  'fullName': 'Melisandre',
  'title': 'Melisandre of Asshai',
  'family': 'Unkown',
  'image': 'melisandre.jpg',
  'imageUrl': 'https://thronesapi.com/assets/images/melisandre.jpg'},
 {'id': 41,
  'firstName': 'Jaqen',
  'lastName': "H'ghar",
  'fullName': "Jaqen H'ghar",
  'title': 'Faceless Men of Braavos',
  'family': 'Lorath',
  'image': 'jaqen-hghar.jpg',
  'imageUrl': 'https://thronesapi.com/assets/images/jaqen-hghar.jpg'},
 {'id': 42,
  'firstName': 'Tywin',
  'lastName': 'Lannister',
  'fullName': 'Tywin Lannister',
  'title': 'Lord Paramount of Westerlands',
  'family': 'Lannister',
  'image': 'tywin-lannister.jpg',
  'imageUrl': 'https://thronesapi.com/assets/images/tywin-lannister.jpg'},
 {'id': 43,
  'firstName': 'Ellaria',
  'lastName': 'Sand',
  'fullName': 'Ellaria Sand',
  'title': 'Paramour of Prince Oberyn Martell',
  'family': 'Sand',
  'image': 'ellaria-sand.jpg',
  'imageUrl': 'https://thronesapi.com/assets/images/ellaria-sand.jpg'},
 {'id': 44,
  'firstName': 'Tormund',
  'lastName': 'Giantsbane',
  'fullName': 'Tormund Giantsbane',
  'title': 'Free Folk Warrior',
  'family': 'Free Folk',
  'image': 'tormund-giantsbane.jpg',
  'imageUrl': 'https://thronesapi.com/assets/images/tormund-giantsbane.jpg'},
 {'id': 45,
  'firstName': 'Yara',
  'lastName': 'Greyjoy',
  'fullName': 'Yara Greyjoy',
  'title': 'Lady of the Iron Islands',
  'family': 'Greyjoy',
  'image': 'yara-greyjoy.jpg',
  'imageUrl': 'https://thronesapi.com/assets/images/yara-greyjoy.jpg'},
 {'id': 46,
  'firstName': 'Euron',
  'lastName': 'Greyjoy',
  'fullName': 'Euron Greyjoy',
  'title': 'King of the iron Islands',
  'family': 'Greyjoy',
  'image': 'euron-greyjoy.jpg',
  'imageUrl': 'https://thronesapi.com/assets/images/euron-greyjoy.jpg'},
 {'id': 47,
  'firstName': 'Wylis',
  'lastName': 'Hodor',
  'fullName': 'Hodor',
  'title': 'Servant of House Stark',
  'family': 'Stark',
  'image': 'hodor.jpg',
  'imageUrl': 'https://thronesapi.com/assets/images/hodor.jpg'},
 {'id': 48,
  'firstName': '',
  'lastName': 'Pycelle',
  'fullName': 'Pycelle',
  'title': 'Grand Maester of the Seven Kingdoms',
  'family': '',
  'image': 'pycelle.jpg',
  'imageUrl': 'https://thronesapi.com/assets/images/pycelle.jpg'},
 {'id': 49,
  'firstName': 'Grey',
  'lastName': 'Worm',
  'fullName': 'Grey Worm',
  'title': 'Commander of the Unsullied',
  'family': 'Worm',
  'image': 'greyworm.jpg',
  'imageUrl': 'https://thronesapi.com/assets/images/greyworm.jpg'},
 {'id': 50,
  'firstName': 'Olenna',
  'lastName': 'Tyrell',
  'fullName': 'Olenna Tyrell',
  'title': 'Queen of Thorns',
  'family': 'Tyrell',
  'image': 'olenna-tyrell.jpg',
  'imageUrl': 'https://thronesapi.com/assets/images/olenna-tyrell.jpg'},
 {'id': 51,
  'firstName': 'Qyburn',
  'lastName': 'Grand Maester',
  'fullName': 'Qyburn',
  'title': 'Former maester of the Citadel',
  'family': 'Qyburn',
  'image': 'qyburn.jpg',
  'imageUrl': 'https://thronesapi.com/assets/images/qyburn.jpg'},
 {'id': 52,
  'firstName': 'Lord',
  'lastName': 'Bronn',
  'fullName': 'Lord Bronn',
  'title': 'Lord of Highgarden',
  'family': 'Bronn',
  'image': 'bronn.jpg',
  'imageUrl': 'https://thronesapi.com/assets/images/bronn.jpg'}]

In [91]:
engine = create_engine(connectionString)
with engine.connect() as connection:
    for item in response.json():
        query = text("""
                     INSERT INTO trono (id, firstName, fullName, title, family, image, imageUrl) 
                     VALUES (:id, :firstName, :fullName, :title, :family, :image, :imageUrl)""")
        
        connection.execute(query, {
            'id': item['id'],
            'firstName': item['firstName'],
            'fullName': item['fullName'],
            'title': item['title'],
            'family': item['family'],
            'image': item['image'],
            'imageUrl': item['imageUrl'],
        })
        connection.commit()

In [93]:
dfPanda = pd.read_sql("SELECT * FROM trono", con=engine)
dfPanda.head()

,index,id,firstName,lastName,fullName,title,family,image,imageUrl
0,None,0,Daenerys,None,Daenerys Targaryen,Mother of Dragons,House Targaryen,daenerys.jpg,https://thronesapi.com/assets/images/daenerys.jpg
1,None,1,Samwell,None,Samwell Tarly,Maester,House Tarly,sam.jpg,https://thronesapi.com/assets/images/sam.jpg
2,None,2,Jon,None,Jon Snow,King of the North,House Stark,jon-snow.jpg,https://thronesapi.com/assets/images/jon-snow.jpg
3,None,3,Arya,None,Arya Stark,No One,House Stark,arya-stark.jpg,https://thronesapi.com/assets/images/arya-star...
4,None,4,Sansa,None,Sansa Stark,Lady of Winterfell,House Stark,sansa-stark.jpeg,https://thronesapi.com/assets/images/sansa-sta...

### Sintaxe para cambiar un parámetro a unha variable de código

In [22]:
state='FINISHED'
%sql SELECT :state as "bind_variable"

Environment variable $DATABASE_URL not set, and no connect string given.
Connection info needed in SQLAlchemy format, example:
               postgresql://username:password@hostname/dbname
               or an existing connection: dict_keys([])

<h1>Neflix<h1>

In [29]:
#import sqlalchemy
from sqlalchemy.engine import create_engine

engine = create_engine(connectionString)

cadeaSQL = "SELECT * FROM netflix"
#result=engine.execute(cadenaSQL)
dfPanda = pd.read_sql(cadeaSQL, engine)
#dfPanda = pd.read_sql("SELECT * FROM salaries", con=connectionString)
dfPanda.head()

Empty DataFrame
Columns: [videoID, country, title1, title2, startTime, collection, image, genre]
Index: []

In [38]:
import json

jasonPath = "netflix.json"

with open(jasonPath, 'r') as file:
	data = json.load(file)["data"]
data

[{'videoID': 81989516,
  'country': 'US',
  'title1': 'Amor en el laboratorio',
  'title2': 'Miniserie',
  'startTime': 1740837600000,
  'collection': 2170013,
  'image': 'https://dnm.nflximg.net/api/v6/mAcAr9TxZIVbINe88xb3Teg5_OA/AAAABZhlREPean3D0eS2Q0-iSVe6Blj_aARPTMsBGLEwjEjs16X03ksOCS-D3mP-CAmtJWpd_Fh_o2aYRK8wQFN9QBxoFzULOr0JYHD3YOscyt0FWKkCIVOEKYxOihYIRqO84KtxIQ.jpg?r=2fe',
  'genre': 1305630},
 {'videoID': 81681666,
  'country': 'US',
  'title1': 'Hot Wheels: ¡Máxima velocidad!',
  'title2': 'Temporada 3',
  'startTime': 1740988800000,
  'collection': 2170013,
  'image': 'https://dnm.nflximg.net/api/v6/mAcAr9TxZIVbINe88xb3Teg5_OA/AAAABaacIVJ2iLkkCbgaQabzxXjpVXzyTAn_u9THnSCf-rdubQHoQRclE2bXa40kZ5dEInLBs9WMZjDWahesBhOCRd4dg60TaQhDc8VYoCQoXA2gfGarxpLHjNhfD5jPvZBUfeqGMQ.jpg?r=30b',
  'genre': 2070367},
 {'videoID': 81770809,
  'country': 'US',
  'title1': 'Con amor, Meghan',
  'title2': 'Temporada 1',
  'startTime': 1741075200000,
  'collection': 2170013,
  'image': 'https://dnm.nflximg.net/api/v6/mAcAr9TxZIVbINe88xb3Teg5_OA/AAAABS8Nh4ad1WxK5cWBpvdTV60ndLNRjBO4vTpcNXyQQOXpoOegR9w3y6x6dbYUBGjQLK_3Mcq6SVwvSjAt9e0NqE8UA8oYslMRh-2Pnzi1Go64ogl69AjGUsQgbKW_pREPtrjqiw.jpg?r=10f',
  'genre': 100199},
 {'videoID': 81664957,
  'country': 'US',
  'title1': 'Solo una mirada',
  'title2': 'Miniserie',
  'startTime': 1741161600000,
  'collection': 2170013,
  'image': 'https://dnm.nflximg.net/api/v6/mAcAr9TxZIVbINe88xb3Teg5_OA/AAAABWuVEfE3L5njqTWSHkfGoZ1mH_-iTEqIVUcDWkuRJk3BUij_JZWafj2Jrs3DgTpB4NfaPD6Xp3kTxTSaefRVE7beP0oQnc2SVdzaQDcEYFUFbLZHdMrqVX98lu-RKeszw4ociw.jpg?r=cba',
  'genre': 81246423},
 {'videoID': 81683617,
  'country': 'US',
  'title1': 'Medusa',
  'title2': 'Temporada 1',
  'startTime': 1741161600000,
  'collection': 2170013,
  'image': 'https://dnm.nflximg.net/api/v6/mAcAr9TxZIVbINe88xb3Teg5_OA/AAAABe6_oYr2hjMMUP-JxKjTfseUC1h7V1aYoZuOpu5NzlQWzu5caoHa5PxARUOmiku4vtY8s5Snd78_s-q5__F5Q2TBRPfZWpoljIw_QhvxK04wZt83C7lupuIXcqyTk0OnGkinPQ.jpg?r=465',
  'genre': 81246423},
 {'videoID': 81392677,
  'country': 'US',
  'title1': 'El gatopardo',
  'title2': 'Miniserie',
  'startTime': 1741161600000,
  'collection': 2170013,
  'image': 'https://dnm.nflximg.net/api/v6/mAcAr9TxZIVbINe88xb3Teg5_OA/AAAABbjOz-h0nIY3W1kc5zA4kQu4PeB09TY4lqqEM7koURLFSJQ03TC0sSqZbwRrlTZfH8gzjiohqCXgz-yAAsf1zJ8lEl34tH19X-YyTzr1FFlFBIHjlJtT-elkbWSeFBwJh6LdeA.jpg?r=db9',
  'genre': 1307182},
 {'videoID': 81681536,
  'country': 'US',
  'title1': 'Si la vida te da mandarinas...',
  'title2': 'Miniserie',
  'startTime': 1741334400000,
  'collection': 2170013,
  'image': 'https://dnm.nflximg.net/api/v6/mAcAr9TxZIVbINe88xb3Teg5_OA/AAAABXOe3Fv5Z1SAv0PpLsa-F4UA9EbZN79jx2Ysl2wna44PGT-JCF6NiDXCDZOQFqTEHVzoEw5gZu6nv1jMzW7z8OgvzKhh3hbdWNAGRUlZFv3kFymXtyifJhRLBWvx_Kq5j_HcFg.jpg?r=ce4',
  'genre': 1307182},
 {'videoID': 81627185,
  'country': 'US',
  'title1': 'Formula 1: Drive to Survive',
  'title2': 'Temporada 7',
  'startTime': 1741334400000,
  'collection': 2170013,
  'image': 'https://dnm.nflximg.net/api/v6/mAcAr9TxZIVbINe88xb3Teg5_OA/AAAABRjnWT5b0Bz8y5kW1yO-Fi5aig31x7Qeal8vaz0za8UZtcrYFUDJJ-8Vs1dnVapM_UibCwLzCfgtxOZ7QOwg6kGhaOVCUglVjaOMlNKYN4cLYCke56BabzEZ_TFFx_7UV1fHbA.jpg?r=708',
  'genre': 100148},
 {'videoID': 81633044,
  'country': 'US',
  'title1': 'Bienvenidos a la familia',
  'title2': 'Temporada 1',
  'startTime': 1741762800000,
  'collection': 2170013,
  'image': 'https://dnm.nflximg.net/api/v6/mAcAr9TxZIVbINe88xb3Teg5_OA/AAAABVoidItPXaEL24dzhKeNrcGKak9WjYEE3t01iFOOAhe-mnPrJ_3HW-wTR8KLMOMQtBUrBMm3Oefbm2LlRcd9Z9ZiaEdKj2wke26WnH53Rb_WT1dgaxRvjPVtQgBnzobCdhShuQ.jpg?r=20e',
  'genre': 81246423},
 {'videoID': 81912997,
  'country': 'US',
  'title1': 'Estamos todos en vivo con John Mulaney',
  'title2': 'Temporada 1',
  'startTime': 1741829400000,
  'collection': 2170013,
  'image': 'https://dnm.nflximg.net/api/v6/mAcAr9TxZIVbINe88xb3Teg5_OA/AAAABW9TtFGevozOkXfSJVM9GqNJ3VeJHcLUzKFbzBlb7lVlXV4x3AybFCTYLWcSGJvVqwGlzKV90vAG1TtjDWImwVeJW6zCLd_l0aIEqeQVVP5IVz5jgp9XOaSXnXsKmxC82Dz9SA.jpg?r=83a',
  'genre': 1305630},
 {'videoID': 81725913,
  'country': 'US',
  'title1': 'El amor es ciego: Suecia',
  'title2': 'Temporada 2',
  'startTime': 1741849200000,
  'collection': 2170013,
  'image': 'https://dnm.nflximg.net/api/v6/mAcAr9TxZIVbINe88xb3Teg5_OA/AAAABdIQ1FmxZpYJyNMQQJvuI5JDbOXJHg-1cU_UBKC4-P4xWH4RX5STG4RxfiYaXSKpXNXwqNijpKOpJBLcY_Q6stS0IHRIVhlUmep6ws3BNT5f_CiAj7qGNofVhxxJonROZBOaqQ.jpg?r=26a',
  'genre': 100199},
 {'videoID': 81756070,
  'country': 'US',
  'title1': 'Adolescencia',
  'title2': 'Miniserie',
  'startTime': 1741849200000,
  'collection': 2170013,
  'image': 'https://dnm.nflximg.net/api/v6/mAcAr9TxZIVbINe88xb3Teg5_OA/AAAABVly4ZcC7-NtzyQiwqTH_3CJCBVPzKbxFqdzGPnO6b1gV_ZU2Nv4g-Ez61DwE5izeaBxME2VwihDSmuC9BLy9N_ewUhRn7UC9MpKQX7T4XLuBM_a2T6cTa8sPVHLNsvWWDa0yw.jpg?r=d6e',
  'genre': 81246423},
 {'videoID': 81516109,
  'country': 'US',
  'title1': 'Calle CoComelon',
  'title2': 'Temporada 4',
  'startTime': 1742194800000,
  'collection': 2170013,
  'image': 'https://dnm.nflximg.net/api/v6/mAcAr9TxZIVbINe88xb3Teg5_OA/AAAABd6OyYkrPHaU-l-qO6SYJXvFtqQqZgSRG5U5_Clh6DAT6mHtEcVFT5am3zWmtHokYy2NkQJjFqzWsdViqNgVI_K97WP6Tc9SR7pNyQzTEKItGBzJ1PojHMlj_AINBEt76OVeYQ.jpg?r=7f7',
  'genre': 2070367},
 {'videoID': 81946747,
  'country': 'US',
  'title1': 'Inside',
  'title2': 'Temporada 2',
  'startTime': 1742194800000,
  'collection': 2170013,
  'image': 'https://dnm.nflximg.net/api/v6/mAcAr9TxZIVbINe88xb3Teg5_OA/AAAABV-KTB6PberCl5csHLndBWeNKgCcx0vUd0Ioa7BxcZ5GkL0jUIGTtOCbL4QjWb_x1O4viNCbqxM5JC29TfkhIwM6oCapR9VV9soEjthhgSHwXsaVfbf34M7IsG7g5m6KxdtVaw.jpg?r=bf2',
  'genre': 100199},
 {'videoID': 81710016,
  'country': 'US',
  'title1': 'Escupiré sobre sus tumbas',
  'title2': 'Temporada 1',
  'startTime': 1742194800000,
  'collection': 2170013,
  'image': 'https://dnm.nflximg.net/api/v6/mAcAr9TxZIVbINe88xb3Teg5_OA/AAAABRWcz8P4oe7sDUf-N7DPReLR6Glxyhbp0Itt4-Ab0JnThj2XbPkjPv3ekzXBIFbkyXiReh0COXIt_kJinKGwBVzKO6IpmmPAuImHyMygGf6rsbND_DafeJh-iwgeI2yrOSve1A.jpg?r=878',
  'genre': 81246423},
 {'videoID': 81717675,
  'country': 'US',
  'title1': 'La dama de los muertos',
  'title2': 'Temporada 2',
  'startTime': 1742367600000,
  'collection': 2170013,
  'image': 'https://dnm.nflximg.net/api/v6/mAcAr9TxZIVbINe88xb3Teg5_OA/AAAABUoYccnQIxCSTppVQ4fN6tMjnjYkqInvjMcOsHWMbHsIBQ2h_tWEgnQzX53UyKLa3SgNR6n_0CoYf2SVKYYZn9eRzYu6sXtPRqX2AxIYyYPyptUSGM6YvCusyXAjcJd0tQaCbw.jpg?r=d0b',
  'genre': 81246423},
 {'videoID': 81708178,
  'country': 'US',
  'title1': 'La apuesta de mi vida',
  'title2': 'Temporada 1',
  'startTime': 1742454000000,
  'collection': 2170013,
  'image': 'https://dnm.nflximg.net/api/v6/mAcAr9TxZIVbINe88xb3Teg5_OA/AAAABaaWEZDwtwEe9LNuax8tqno3m7iBEp02Z3I1AL912oTFHGEDnAyoum90MlvIhyLzgnrc4dDlzJlIRmEjnzyJq3X6Z00eyX0XlcQWdVkrc-MEtAnovSfWvvbTCAXvC8QZ-XzbGQ.jpg?r=914',
  'genre': 1305630},
 {'videoID': 81271209,
  'country': 'US',
  'title1': 'Rey lobo',
  'title2': 'Temporada 1',
  'startTime': 1742454000000,
  'collection': 2170013,
  'image': 'https://dnm.nflximg.net/api/v6/mAcAr9TxZIVbINe88xb3Teg5_OA/AAAABWw7FX5eqvTEtoIVkyi1XtV1_waFEP6lqsSi2CciW74LIXcuorXnbH3vjdyC_6KzbyU6RpxmCoAwiPpCpIuNvdXQjyrXn3hmPeHUIEr-ObdeK8kEqB-RaO9qh4J0sWGGgDSLwg.jpg?r=4ce',
  'genre': 2070367},
 {'videoID': 81011440,
  'country': 'US',
  'title1': 'La residencia',
  'title2': 'Temporada 1',
  'startTime': 1742454000000,
  'collection': 2170013,
  'image': 'https://dnm.nflximg.net/api/v6/mAcAr9TxZIVbINe88xb3Teg5_OA/AAAABf0nxkBq2I3ZltF1OJaPK6r8Zw6i9rjWT_KrRX_eOPhDAv2FGoMW6tNNVehROpEhVnoDLJm6k3aGGSspYlZTU9GOlOwYiq-yuONXAI7FSZzKEaftl-iHO1hjzrDd09grr6MMOA.jpg?r=284',
  'genre': 81325761},
 {'videoID': 81446377,
  'country': 'US',
  'title1': 'Policía: El capítulo en Bengala',
  'title2': 'Temporada 1',
  'startTime': 1742454000000,
  'collection': 2170013,
  'image': 'https://dnm.nflximg.net/api/v6/mAcAr9TxZIVbINe88xb3Teg5_OA/AAAABXDUREPkqUHGYYrj2TC5hCkedQF0eZz1b30p0hXKnvVWAvjt__Ek2Gs3v3wjFhsoTh4wHsJ2k99urElEI4qAHk6Jo4QZ3P-nYpNoWl23r4244a_jMwklDl8st9KXqoovljC7vQ.jpg?r=eeb',
  'genre': 81246423}]

In [40]:
engine = create_engine(connectionString)
with engine.connect() as connection:
    for item in data:
        query = text("""
                     INSERT INTO netflix (videoId, country, title1, title2, startTime, collection, image, genre) 
                     VALUES (:videoId, :country, :title1, :title2, :startTime, :collection, :image, :genre)""")
        
     connection.execute(query, {
            'videoId': item['videoId'],
            'country': item['country'],
            'title1': item['title1'],
            'title2': item['title2'],
            'startTime': item['startTime'],
            'collection': item['collection'],
            'image': item['image'],
            'genre': item['genre'],
        })

connection.commit()

IndentationError: unindent does not match any outer indentation level (<string>, line 8)

# Converter a .parquet

## Instalación das librarías

Empregamos un PANDAS DataFrame e convertirémolo a un arquivo .parquet

Fai falta instalar con conda as librarías:
* pyarrow
* fastparquet

**Aviso**: Non é a forma máis recomendada de conversión

In [2]:
%conda install -y pyarrow fastparquet

Channels:
 - defaults
 - conda-forge
Platform: linux-64
Collecting package metadata (repodata.json): -

## Conversión a parquet

In [ ]:
dfPanda.to_parquet("salaries.parquet")

## Abrir o novo arquivo .parquet
Cargámolo en memoria para comprobar que se xerou correctamente

In [ ]:
df = pd.read_parquet("salaries.parquet")
df.head(5)